---

# 参考文献
#   - https://docs.docker.com/engine/install/debian/#install-using-the-repository
#   - https://docs.docker.com/compose/install/
- hosts: all
  become: true
  tasks:
    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
    
    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Get cpu architecture
      shell: dpkg --print-architecture
      register: cpu_architecture_from_shell
      changed_when: false  # 環境情報を取得するだけであるため

    - name: Debug cpu_architecture_from_shell.stdout
      debug: msg="{{ cpu_architecture_from_shell.stdout }}"

    - name: Get os version
      shell: lsb_release -cs
      register: os_version_from_shell
      changed_when: false  # 環境情報を取得するだけであるため

    - name: Debug os_version_from_shell.stdout
      debug: msg="{{ os_version_from_shell.stdout }}"

    - name: Set up stable repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ cpu_architecture_from_shell.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ os_version_from_shell.stdout }} stable
        state: present
        filename: docker

    - name: Install docker
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Install Docker SDK for python and Docker Compose
      pip:
        name:
          - docker  # AnsibleからDockerを触る際に必要
          - docker-compose
